server.port=8090

# Configuración de la base de datos
spring.datasource.url=jdbc:mysql://mysql:3306/kartingrm  # Cambié localhost por mysql
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
